// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KVList.proto

package site.dwei.util;

public final class KVListSerial {
  private KVListSerial() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KVListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KVList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    java.util.List<site.dwei.util.KVListSerial.KVList.KVText> 
        getKvtextsList();
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    site.dwei.util.KVListSerial.KVList.KVText getKvtexts(int index);
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    int getKvtextsCount();
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    java.util.List<? extends site.dwei.util.KVListSerial.KVList.KVTextOrBuilder> 
        getKvtextsOrBuilderList();
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    site.dwei.util.KVListSerial.KVList.KVTextOrBuilder getKvtextsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code KVList}
   */
  public  static final class KVList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KVList)
      KVListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVList.newBuilder() to construct.
    private KVList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVList() {
      kvtexts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KVList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KVList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                kvtexts_ = new java.util.ArrayList<site.dwei.util.KVListSerial.KVList.KVText>();
                mutable_bitField0_ |= 0x00000001;
              }
              kvtexts_.add(
                  input.readMessage(site.dwei.util.KVListSerial.KVList.KVText.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          kvtexts_ = java.util.Collections.unmodifiableList(kvtexts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.dwei.util.KVListSerial.internal_static_KVList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.dwei.util.KVListSerial.internal_static_KVList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.dwei.util.KVListSerial.KVList.class, site.dwei.util.KVListSerial.KVList.Builder.class);
    }

    public interface KVTextOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KVList.KVText)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>int64 value = 2;</code>
       * @return The value.
       */
      long getValue();
    }
    /**
     * Protobuf type {@code KVList.KVText}
     */
    public  static final class KVText extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:KVList.KVText)
        KVTextOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use KVText.newBuilder() to construct.
      private KVText(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private KVText() {
        key_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new KVText();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private KVText(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                key_ = s;
                break;
              }
              case 16: {

                value_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.dwei.util.KVListSerial.internal_static_KVList_KVText_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.dwei.util.KVListSerial.internal_static_KVList_KVText_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.dwei.util.KVListSerial.KVList.KVText.class, site.dwei.util.KVListSerial.KVList.KVText.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private long value_;
      /**
       * <code>int64 value = 2;</code>
       * @return The value.
       */
      public long getValue() {
        return value_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getKeyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (value_ != 0L) {
          output.writeInt64(2, value_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getKeyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (value_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof site.dwei.util.KVListSerial.KVList.KVText)) {
          return super.equals(obj);
        }
        site.dwei.util.KVListSerial.KVList.KVText other = (site.dwei.util.KVListSerial.KVList.KVText) obj;

        if (!getKey()
            .equals(other.getKey())) return false;
        if (getValue()
            != other.getValue()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static site.dwei.util.KVListSerial.KVList.KVText parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(site.dwei.util.KVListSerial.KVList.KVText prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code KVList.KVText}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:KVList.KVText)
          site.dwei.util.KVListSerial.KVList.KVTextOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return site.dwei.util.KVListSerial.internal_static_KVList_KVText_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return site.dwei.util.KVListSerial.internal_static_KVList_KVText_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  site.dwei.util.KVListSerial.KVList.KVText.class, site.dwei.util.KVListSerial.KVList.KVText.Builder.class);
        }

        // Construct using site.dwei.util.KVListSerial.KVList.KVText.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";

          value_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return site.dwei.util.KVListSerial.internal_static_KVList_KVText_descriptor;
        }

        @java.lang.Override
        public site.dwei.util.KVListSerial.KVList.KVText getDefaultInstanceForType() {
          return site.dwei.util.KVListSerial.KVList.KVText.getDefaultInstance();
        }

        @java.lang.Override
        public site.dwei.util.KVListSerial.KVList.KVText build() {
          site.dwei.util.KVListSerial.KVList.KVText result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public site.dwei.util.KVListSerial.KVList.KVText buildPartial() {
          site.dwei.util.KVListSerial.KVList.KVText result = new site.dwei.util.KVListSerial.KVList.KVText(this);
          result.key_ = key_;
          result.value_ = value_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof site.dwei.util.KVListSerial.KVList.KVText) {
            return mergeFrom((site.dwei.util.KVListSerial.KVList.KVText)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(site.dwei.util.KVListSerial.KVList.KVText other) {
          if (other == site.dwei.util.KVListSerial.KVList.KVText.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            onChanged();
          }
          if (other.getValue() != 0L) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          site.dwei.util.KVListSerial.KVList.KVText parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (site.dwei.util.KVListSerial.KVList.KVText) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 1;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          key_ = value;
          onChanged();
          return this;
        }

        private long value_ ;
        /**
         * <code>int64 value = 2;</code>
         * @return The value.
         */
        public long getValue() {
          return value_;
        }
        /**
         * <code>int64 value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(long value) {
          
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          
          value_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:KVList.KVText)
      }

      // @@protoc_insertion_point(class_scope:KVList.KVText)
      private static final site.dwei.util.KVListSerial.KVList.KVText DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new site.dwei.util.KVListSerial.KVList.KVText();
      }

      public static site.dwei.util.KVListSerial.KVList.KVText getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<KVText>
          PARSER = new com.google.protobuf.AbstractParser<KVText>() {
        @java.lang.Override
        public KVText parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new KVText(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<KVText> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<KVText> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public site.dwei.util.KVListSerial.KVList.KVText getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int KVTEXTS_FIELD_NUMBER = 1;
    private java.util.List<site.dwei.util.KVListSerial.KVList.KVText> kvtexts_;
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    public java.util.List<site.dwei.util.KVListSerial.KVList.KVText> getKvtextsList() {
      return kvtexts_;
    }
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    public java.util.List<? extends site.dwei.util.KVListSerial.KVList.KVTextOrBuilder> 
        getKvtextsOrBuilderList() {
      return kvtexts_;
    }
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    public int getKvtextsCount() {
      return kvtexts_.size();
    }
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    public site.dwei.util.KVListSerial.KVList.KVText getKvtexts(int index) {
      return kvtexts_.get(index);
    }
    /**
     * <code>repeated .KVList.KVText kvtexts = 1;</code>
     */
    public site.dwei.util.KVListSerial.KVList.KVTextOrBuilder getKvtextsOrBuilder(
        int index) {
      return kvtexts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < kvtexts_.size(); i++) {
        output.writeMessage(1, kvtexts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < kvtexts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, kvtexts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.dwei.util.KVListSerial.KVList)) {
        return super.equals(obj);
      }
      site.dwei.util.KVListSerial.KVList other = (site.dwei.util.KVListSerial.KVList) obj;

      if (!getKvtextsList()
          .equals(other.getKvtextsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getKvtextsCount() > 0) {
        hash = (37 * hash) + KVTEXTS_FIELD_NUMBER;
        hash = (53 * hash) + getKvtextsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.dwei.util.KVListSerial.KVList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.dwei.util.KVListSerial.KVList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static site.dwei.util.KVListSerial.KVList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static site.dwei.util.KVListSerial.KVList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.dwei.util.KVListSerial.KVList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KVList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KVList)
        site.dwei.util.KVListSerial.KVListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.dwei.util.KVListSerial.internal_static_KVList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.dwei.util.KVListSerial.internal_static_KVList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.dwei.util.KVListSerial.KVList.class, site.dwei.util.KVListSerial.KVList.Builder.class);
      }

      // Construct using site.dwei.util.KVListSerial.KVList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getKvtextsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (kvtextsBuilder_ == null) {
          kvtexts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          kvtextsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.dwei.util.KVListSerial.internal_static_KVList_descriptor;
      }

      @java.lang.Override
      public site.dwei.util.KVListSerial.KVList getDefaultInstanceForType() {
        return site.dwei.util.KVListSerial.KVList.getDefaultInstance();
      }

      @java.lang.Override
      public site.dwei.util.KVListSerial.KVList build() {
        site.dwei.util.KVListSerial.KVList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.dwei.util.KVListSerial.KVList buildPartial() {
        site.dwei.util.KVListSerial.KVList result = new site.dwei.util.KVListSerial.KVList(this);
        int from_bitField0_ = bitField0_;
        if (kvtextsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            kvtexts_ = java.util.Collections.unmodifiableList(kvtexts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.kvtexts_ = kvtexts_;
        } else {
          result.kvtexts_ = kvtextsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.dwei.util.KVListSerial.KVList) {
          return mergeFrom((site.dwei.util.KVListSerial.KVList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.dwei.util.KVListSerial.KVList other) {
        if (other == site.dwei.util.KVListSerial.KVList.getDefaultInstance()) return this;
        if (kvtextsBuilder_ == null) {
          if (!other.kvtexts_.isEmpty()) {
            if (kvtexts_.isEmpty()) {
              kvtexts_ = other.kvtexts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKvtextsIsMutable();
              kvtexts_.addAll(other.kvtexts_);
            }
            onChanged();
          }
        } else {
          if (!other.kvtexts_.isEmpty()) {
            if (kvtextsBuilder_.isEmpty()) {
              kvtextsBuilder_.dispose();
              kvtextsBuilder_ = null;
              kvtexts_ = other.kvtexts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              kvtextsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKvtextsFieldBuilder() : null;
            } else {
              kvtextsBuilder_.addAllMessages(other.kvtexts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        site.dwei.util.KVListSerial.KVList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (site.dwei.util.KVListSerial.KVList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<site.dwei.util.KVListSerial.KVList.KVText> kvtexts_ =
        java.util.Collections.emptyList();
      private void ensureKvtextsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          kvtexts_ = new java.util.ArrayList<site.dwei.util.KVListSerial.KVList.KVText>(kvtexts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          site.dwei.util.KVListSerial.KVList.KVText, site.dwei.util.KVListSerial.KVList.KVText.Builder, site.dwei.util.KVListSerial.KVList.KVTextOrBuilder> kvtextsBuilder_;

      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public java.util.List<site.dwei.util.KVListSerial.KVList.KVText> getKvtextsList() {
        if (kvtextsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(kvtexts_);
        } else {
          return kvtextsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public int getKvtextsCount() {
        if (kvtextsBuilder_ == null) {
          return kvtexts_.size();
        } else {
          return kvtextsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public site.dwei.util.KVListSerial.KVList.KVText getKvtexts(int index) {
        if (kvtextsBuilder_ == null) {
          return kvtexts_.get(index);
        } else {
          return kvtextsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder setKvtexts(
          int index, site.dwei.util.KVListSerial.KVList.KVText value) {
        if (kvtextsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvtextsIsMutable();
          kvtexts_.set(index, value);
          onChanged();
        } else {
          kvtextsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder setKvtexts(
          int index, site.dwei.util.KVListSerial.KVList.KVText.Builder builderForValue) {
        if (kvtextsBuilder_ == null) {
          ensureKvtextsIsMutable();
          kvtexts_.set(index, builderForValue.build());
          onChanged();
        } else {
          kvtextsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder addKvtexts(site.dwei.util.KVListSerial.KVList.KVText value) {
        if (kvtextsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvtextsIsMutable();
          kvtexts_.add(value);
          onChanged();
        } else {
          kvtextsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder addKvtexts(
          int index, site.dwei.util.KVListSerial.KVList.KVText value) {
        if (kvtextsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvtextsIsMutable();
          kvtexts_.add(index, value);
          onChanged();
        } else {
          kvtextsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder addKvtexts(
          site.dwei.util.KVListSerial.KVList.KVText.Builder builderForValue) {
        if (kvtextsBuilder_ == null) {
          ensureKvtextsIsMutable();
          kvtexts_.add(builderForValue.build());
          onChanged();
        } else {
          kvtextsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder addKvtexts(
          int index, site.dwei.util.KVListSerial.KVList.KVText.Builder builderForValue) {
        if (kvtextsBuilder_ == null) {
          ensureKvtextsIsMutable();
          kvtexts_.add(index, builderForValue.build());
          onChanged();
        } else {
          kvtextsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder addAllKvtexts(
          java.lang.Iterable<? extends site.dwei.util.KVListSerial.KVList.KVText> values) {
        if (kvtextsBuilder_ == null) {
          ensureKvtextsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, kvtexts_);
          onChanged();
        } else {
          kvtextsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder clearKvtexts() {
        if (kvtextsBuilder_ == null) {
          kvtexts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          kvtextsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public Builder removeKvtexts(int index) {
        if (kvtextsBuilder_ == null) {
          ensureKvtextsIsMutable();
          kvtexts_.remove(index);
          onChanged();
        } else {
          kvtextsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public site.dwei.util.KVListSerial.KVList.KVText.Builder getKvtextsBuilder(
          int index) {
        return getKvtextsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public site.dwei.util.KVListSerial.KVList.KVTextOrBuilder getKvtextsOrBuilder(
          int index) {
        if (kvtextsBuilder_ == null) {
          return kvtexts_.get(index);  } else {
          return kvtextsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public java.util.List<? extends site.dwei.util.KVListSerial.KVList.KVTextOrBuilder> 
           getKvtextsOrBuilderList() {
        if (kvtextsBuilder_ != null) {
          return kvtextsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(kvtexts_);
        }
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public site.dwei.util.KVListSerial.KVList.KVText.Builder addKvtextsBuilder() {
        return getKvtextsFieldBuilder().addBuilder(
            site.dwei.util.KVListSerial.KVList.KVText.getDefaultInstance());
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public site.dwei.util.KVListSerial.KVList.KVText.Builder addKvtextsBuilder(
          int index) {
        return getKvtextsFieldBuilder().addBuilder(
            index, site.dwei.util.KVListSerial.KVList.KVText.getDefaultInstance());
      }
      /**
       * <code>repeated .KVList.KVText kvtexts = 1;</code>
       */
      public java.util.List<site.dwei.util.KVListSerial.KVList.KVText.Builder> 
           getKvtextsBuilderList() {
        return getKvtextsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          site.dwei.util.KVListSerial.KVList.KVText, site.dwei.util.KVListSerial.KVList.KVText.Builder, site.dwei.util.KVListSerial.KVList.KVTextOrBuilder> 
          getKvtextsFieldBuilder() {
        if (kvtextsBuilder_ == null) {
          kvtextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              site.dwei.util.KVListSerial.KVList.KVText, site.dwei.util.KVListSerial.KVList.KVText.Builder, site.dwei.util.KVListSerial.KVList.KVTextOrBuilder>(
                  kvtexts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          kvtexts_ = null;
        }
        return kvtextsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KVList)
    }

    // @@protoc_insertion_point(class_scope:KVList)
    private static final site.dwei.util.KVListSerial.KVList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.dwei.util.KVListSerial.KVList();
    }

    public static site.dwei.util.KVListSerial.KVList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KVList>
        PARSER = new com.google.protobuf.AbstractParser<KVList>() {
      @java.lang.Override
      public KVList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KVList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KVList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KVList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.dwei.util.KVListSerial.KVList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KVList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KVList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KVList_KVText_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KVList_KVText_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014KVList.proto\"O\n\006KVList\022\037\n\007kvtexts\030\001 \003(" +
      "\0132\016.KVList.KVText\032$\n\006KVText\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\003B\036\n\016site.dwei.utilB\014KVLis" +
      "tSerialb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_KVList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KVList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KVList_descriptor,
        new java.lang.String[] { "Kvtexts", });
    internal_static_KVList_KVText_descriptor =
      internal_static_KVList_descriptor.getNestedTypes().get(0);
    internal_static_KVList_KVText_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KVList_KVText_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
